import json
import logging

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.database import get_db
from app.models.admin import Admin
from app.models.site_config import SiteConfig
from app.routers.admin import get_current_admin
from app.utils.response import success
from app.utils.translator import translate_site_config

logger = logging.getLogger(__name__)

router = APIRouter(tags=["site-config"])

# All configurable keys with defaults
DEFAULTS = {
    # ─── 公司基本信息 ───
    "company_name": "上海铸造有限公司",
    "company_name_en": "SHD Casting Co., Ltd",
    "address": "上海市奉贤区工业园区铸造路88号",
    "address_en": "No.88 Casting Road, Fengxian Industrial Zone, Shanghai",
    "zipcode": "201499",
    "phone": "+86 21 1234 5678",
    "phone_sales": "+86 135 0000 1234",
    "email": "info@shdcasting.com",
    "email_sales": "sales@shdcasting.com",
    "work_hours": "08:30 - 17:30",
    "work_hours_weekend": "09:00 - 12:00",
    "company_intro": "上海铸造有限公司成立于2004年，是一家集研发、生产、销售于一体的专业铸件制造企业，坐落于上海市奉贤工业园区，占地面积约50,000平方米。",

    # ─── 首页 Hero ───
    "hero_tag": "专业铸件制造商 · 20年品质保障",
    "hero_title": "精密铸造\n铸就品质",
    "hero_subtitle": "专业生产灰铸铁、球墨铸铁、铸钢及铝合金铸件，服务全球工业制造业，年产能超过50,000吨。",

    # ─── 首页统计数字 ───
    "stat_years": "20+",
    "stat_years_label": "年行业经验",
    "stat_clients": "5,000+",
    "stat_clients_label": "合作客户",
    "stat_countries": "30+",
    "stat_countries_label": "出口国家",
    "stat_cert": "ISO9001",
    "stat_cert_label": "质量认证",

    # ─── 工厂数据 ───
    "factory_area": "50,000㎡",
    "factory_lines": "5条",
    "factory_capacity": "50,000吨",
    "factory_staff": "200+",

    # ─── 核心优势 (JSON数组) ───
    "advantages": json.dumps([
        {"title": "严格质量管控", "desc": "通过ISO 9001:2015质量管理体系认证，全程追溯每一批次铸件质量。"},
        {"title": "先进生产设备", "desc": "引进国内外先进铸造设备，自动化生产线确保产品一致性与精度。"},
        {"title": "快速交货能力", "desc": "成熟的供应链管理体系，标准件3-7天，定制件15-30天交货。"},
        {"title": "全球出口经验", "desc": "产品畅销欧美、东南亚30余个国家和地区，熟悉国际贸易规则。"},
    ], ensure_ascii=False),

    # ─── 资质认证 (JSON数组) ───
    "certifications": json.dumps([
        {"name": "ISO 9001:2015", "desc": "质量管理体系认证"},
        {"name": "CE认证", "desc": "欧洲产品合规认证"},
        {"name": "SGS认证", "desc": "全球领先检测机构认证"},
        {"name": "BV检验", "desc": "法国必维国际检验认证"},
        {"name": "TÜV认证", "desc": "德国技术监督协会认证"},
    ], ensure_ascii=False),

    # ─── 发展历程 (JSON数组) ───
    "milestones": json.dumps([
        {"year": "2004", "title": "公司成立", "desc": "上海铸造有限公司在上海奉贤区正式成立，首批员工50人。"},
        {"year": "2007", "title": "首次通过ISO认证", "desc": "取得ISO 9001质量管理体系认证，质量管理走向规范化。"},
        {"year": "2010", "title": "产能突破10,000吨", "desc": "新增生产线，年产能突破10,000吨，开始出口东南亚市场。"},
        {"year": "2015", "title": "欧美市场拓展", "desc": "产品进入欧洲、北美市场，出口额占总营收40%以上。"},
        {"year": "2019", "title": "智能化升级", "desc": "引进智能铸造生产线，自动化率达到75%，效率提升显著。"},
        {"year": "2024", "title": "20周年腾飞", "desc": "年产能达50,000吨，员工超500人，服务全球30+国家客户。"},
    ], ensure_ascii=False),

    # ─── 管理团队 (JSON数组) ───
    "team": json.dumps([
        {"name": "张建国", "title": "董事长 & 总经理", "exp": "30年铸造行业经验"},
        {"name": "李明华", "title": "技术总监", "exp": "高级工程师，发明专利12项"},
        {"name": "王秀芳", "title": "质量总监", "exp": "ISO认证内审员，从业25年"},
        {"name": "陈志远", "title": "销售总监", "exp": "海外市场拓展专家"},
    ], ensure_ascii=False),

    # ─── 常见问题 (JSON数组) ───
    "faqs": json.dumps([
        {"q": "最小起订量是多少？", "a": "我们的最小起订量根据产品规格不同而有所差异，一般单品种最低起订1吨或50件（以重量较大者为准）。样品订单可协商。"},
        {"q": "交货周期一般是多长时间？", "a": "标准产品一般3-7个工作日；定制化产品根据复杂程度，通常需要15-30个工作日；大批量订单另行协商。"},
        {"q": "是否提供样品服务？", "a": "是的，我们提供付费样品服务。样品费用在签订正式合同后可从首批货款中扣除。"},
        {"q": "是否接受定制化订单？", "a": "我们接受各类定制化铸件订单，包括特殊材质、特殊尺寸、特殊工艺等。请提供图纸或详细规格，我们将为您评估并报价。"},
    ], ensure_ascii=False),

    # ─── 导航栏 ───
    "navbar_tag": "专业铸件制造商 · 20年行业经验",

    # ─── 多语言翻译占位 (auto-generated by DeepSeek) ───
    "company_intro_en": "", "company_intro_es": "", "company_intro_ru": "",
    "hero_tag_en": "", "hero_tag_es": "", "hero_tag_ru": "",
    "hero_title_en": "", "hero_title_es": "", "hero_title_ru": "",
    "hero_subtitle_en": "", "hero_subtitle_es": "", "hero_subtitle_ru": "",
    "stat_years_label_en": "", "stat_years_label_es": "", "stat_years_label_ru": "",
    "stat_clients_label_en": "", "stat_clients_label_es": "", "stat_clients_label_ru": "",
    "stat_countries_label_en": "", "stat_countries_label_es": "", "stat_countries_label_ru": "",
    "stat_cert_label_en": "", "stat_cert_label_es": "", "stat_cert_label_ru": "",
    "navbar_tag_en": "", "navbar_tag_es": "", "navbar_tag_ru": "",
    "advantages_en": "", "advantages_es": "", "advantages_ru": "",
    "milestones_en": "", "milestones_es": "", "milestones_ru": "",
    "certifications_en": "", "certifications_es": "", "certifications_ru": "",
    "team_en": "", "team_es": "", "team_ru": "",
    "faqs_en": "", "faqs_es": "", "faqs_ru": "",
}


def _get_value(db: Session, key: str) -> str:
    row = db.query(SiteConfig).filter(SiteConfig.key == key).first()
    return row.value if row and row.value else DEFAULTS.get(key, "")


@router.get("/site-config")
def get_site_config(db: Session = Depends(get_db)):
    config = {}
    for key in DEFAULTS:
        config[key] = _get_value(db, key)
    return success(data=config)


class SiteConfigUpdate(BaseModel):
    config: dict[str, str]


@router.put("/admin/site-config")
def admin_update_site_config(body: SiteConfigUpdate, db: Session = Depends(get_db), admin: Admin = Depends(get_current_admin)):
    # 1. Save user-submitted config
    saved = {}
    for key, value in body.config.items():
        if key not in DEFAULTS:
            continue
        row = db.query(SiteConfig).filter(SiteConfig.key == key).first()
        if row:
            row.value = value
        else:
            db.add(SiteConfig(key=key, value=value))
        saved[key] = value
    db.commit()

    # 2. Auto-translate Chinese content to en/es/ru via DeepSeek
    try:
        translations = translate_site_config(saved)
        if translations:
            for key, value in translations.items():
                if key not in DEFAULTS:
                    continue
                row = db.query(SiteConfig).filter(SiteConfig.key == key).first()
                if row:
                    row.value = value
                else:
                    db.add(SiteConfig(key=key, value=value))
            db.commit()
            logger.info(f"Auto-translation completed: {len(translations)} keys")
    except Exception as e:
        logger.error(f"Auto-translation failed (config saved anyway): {e}")

    return success(message="更新成功")
