"""add site_config table

Revision ID: 849309e198fe
Revises: a76e6fd2455f
Create Date: 2026-04-30 00:27:49.519221
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '849309e198fe'
down_revision: Union[str, None] = 'a76e6fd2455f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键名'),
    sa.Column('value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_config')
    # ### end Alembic commands ###
