"""initial tables

Revision ID: a76e6fd2455f
Revises: 
Create Date: 2026-04-29 23:16:46.391332
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a76e6fd2455f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False, comment='bcrypt加密'),
    sa.Column('role', sa.Enum('super_admin', 'sales', 'editor', name='admin_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_fail_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inquiry_id', sa.String(length=20), nullable=False, comment='询价编号 INQ-YYYY-XXXX'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='客户姓名'),
    sa.Column('company', sa.String(length=200), nullable=True, comment='公司名称'),
    sa.Column('email', sa.String(length=200), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='电话'),
    sa.Column('product_category', sa.String(length=100), nullable=True, comment='产品类别'),
    sa.Column('quantity', sa.String(length=100), nullable=True, comment='预计采购量'),
    sa.Column('message', sa.Text(), nullable=False, comment='详细需求'),
    sa.Column('status', sa.Enum('pending', 'processing', 'replied', 'closed', name='inquiry_status'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False, comment='来源渠道'),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True, comment='内部备注'),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id')
    )
    op.create_index('idx_created_at', 'inquiries', ['created_at'], unique=False)
    op.create_index('idx_email', 'inquiries', ['email'], unique=False)
    op.create_index('idx_status', 'inquiries', ['status'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('name_en', sa.String(length=100), nullable=True, comment='英文名称'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='产品名称'),
    sa.Column('name_en', sa.String(length=200), nullable=True, comment='英文名称'),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=200), nullable=True, comment='材质规格'),
    sa.Column('weight_range', sa.String(length=100), nullable=True, comment='重量范围'),
    sa.Column('standard', sa.String(length=100), nullable=True, comment='执行标准'),
    sa.Column('description', sa.Text(), nullable=True, comment='产品描述'),
    sa.Column('cover_image', sa.String(length=500), nullable=True, comment='封面图URL'),
    sa.Column('images', sa.JSON(), nullable=True, comment='多图URL数组'),
    sa.Column('tag', sa.String(length=50), nullable=True, comment='标签'),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('product_categories')
    op.drop_index('idx_status', table_name='inquiries')
    op.drop_index('idx_email', table_name='inquiries')
    op.drop_index('idx_created_at', table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_table('admins')
    # ### end Alembic commands ###
