"""add i18n fields to products and categories

Revision ID: e92a49ce158a
Revises: 849309e198fe
Create Date: 2026-04-30 20:37:36.153299
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e92a49ce158a'
down_revision: Union[str, None] = '849309e198fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_categories', sa.Column('name_es', sa.String(length=100), nullable=True, comment='西语名称'))
    op.add_column('product_categories', sa.Column('name_ru', sa.String(length=100), nullable=True, comment='俄语名称'))
    op.add_column('products', sa.Column('name_es', sa.String(length=200), nullable=True, comment='西语名称'))
    op.add_column('products', sa.Column('name_ru', sa.String(length=200), nullable=True, comment='俄语名称'))
    op.add_column('products', sa.Column('description_en', sa.Text(), nullable=True, comment='英文描述'))
    op.add_column('products', sa.Column('description_es', sa.Text(), nullable=True, comment='西语描述'))
    op.add_column('products', sa.Column('description_ru', sa.Text(), nullable=True, comment='俄语描述'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description_ru')
    op.drop_column('products', 'description_es')
    op.drop_column('products', 'description_en')
    op.drop_column('products', 'name_ru')
    op.drop_column('products', 'name_es')
    op.drop_column('product_categories', 'name_ru')
    op.drop_column('product_categories', 'name_es')
    # ### end Alembic commands ###
